# @package _global_
defaults:
 - /args/analyzer_args: default
 - override /args/model_args: efficientnet-b4
 - override /args/data_args: tobacco3482_384

args:
  model_args:
    checkpoint_state_dict_key: model
  data_args:
    data_loader_args:
      per_device_train_batch_size: 2
      per_device_eval_batch_size: 2
      pin_memory: True
      max_test_samples: 700
  analyzer_args:
    model_checkpoints:
      - ['baseline', https://cloud.dfki.de/owncloud/index.php/s/RrJTkJdbJ4s4mX7/download/docshap_efficientnet-b4_tobacco.ckpt]
    tasks:
      # evaluation:
      #   task_type: generate_metrics
      #   task_config:
      #     metrics:
      #       - accuracy
      image_attr_analysis:
        task_type: image_attr_analysis
        task_config:
          methods:
            saliency:
              batch_size: 8
              normalize: False
            input_x_gradient:
              batch_size: 8
              normalize: False
            guided_backprop:
              batch_size: 8
              normalize: False
            deeplift:
              batch_size: 8
              apply_baseline: False
              normalize: False
            integrated_gradients:
              batch_size: 8
              apply_noise_tunnel: False
              n_steps: 100
              normalize: False
            deepshap:
              batch_size: 8
              internal_batch_size: 10
              normalize: False
            occlusion:
              batch_size: 8
              baseline_value: 0
              strides: [3, 16, 16]
              sliding_window_shapes: [3, 32, 32]
              normalize: False
            lime:
              batch_size: 8
              normalize: False
            kernel_shap:
              batch_size: 8
              normalize: False
          evaluators:
            attr_map:
              visualize: False
              overwrite: False
            # continuity: {}
            # infidelity: {}
            # sensitivity: {}
            feature_perturbation:
              overwrite: True
              perturbation_kwargs:
                attr_map_grid_cell_size: 24
                attr_map_reduce_fn: mean
                # max_perturbation_percentage: 1.0
                perturbation_step_size: 1
                max_perturbation_steps: 100
                eval_batch_size: 256
                force_gray_to_rgb: True
                normalize_attributions: false
                attack_type: black_white_dropout
                attack_config: {}
            aopc:
              overwrite: True